### PR TITLE
devise setup

### PR DESCRIPTION
**Pull request by Shimunta**
@cbeck

### CODE REVIEW

**Comment by cbeck** [comment]
👍

**Comment by cbeck** [comment]
looks like I am not a collaborator - you tagged me in the PR, but I can't merge it.

**Comment by cbeck** [comment]
it's per-project, btw.

**Comment by Shimunta** [comment]
i added you in the section again. We had this issue last time?

**Comment by cbeck** [comment]
We did, but I think all you might have done is add my @cbeck id to the commit in the message. So I got notified, but I can't actually merge it unless you go to settings/collaborators for this project and add me as a collaborator here. Don't worry - we can straighten it out on our call.

**Pull request merged**
